apiVersion: v1
kind: Service
metadata:
  name: tomcat9-redis-single-svcnp
spec:
  type: NodePort
  selector:
    run: tomcat9-redis-single
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
